export const REORDER = 'REORDER';
export const MOVE = 'MOVE';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const SELECT = 'SELECT';
export const UNSELECT_ALL = 'UNSELECT_ALL';
export const MULTI_DRAG_SINGLE_DESTINATION = 'MULTI_DRAG_SINGLE_DESTINATION';