export const LOADING_STARTED = 'LOADING_STARTED';
export const SUCCESS_WITH_RESULT = 'SUCCESS_WITH_RESULT';
export const ERROR = 'ERROR';
export const LOADING_FINISHED = 'LOADING_FINISHED';
export const DRAG_AND_DROP = 'DRAG_AND_DROP';